# CodeRabbit AI Code Review Configuration
# Get your free API key at https://coderabbit.ai

# Disable by default since it requires API key
# To enable:
# 1. Sign up at coderabbit.ai
# 2. Get your API key
# 3. Add to GitHub secrets: API_KEY_CODERABBIT

review:
  high_level_summary: true
  auto_title_placeholder: ""
  poem: false
  review_status: true
  collapse_walkthrough: false
  sequence_diagrams: true

checks:
  todos:
    resolved: false

chat:
  auto_reply: true

categories:
  suggest_quality_unsafe: false
  security: true

paths:
  exclude:
    - "**/*.md"
    - "**/charts/**"
    - "**/vendor/**"

metadata:
  org: H3xKatana
  repo: k8s-production-template
